[package]
name = "unidecode-compress"
version = "0.1.0"
authors = ["Kornel <kornel@geekhood.net>"]

[[bin]]
name = "compress"
path = "compress.rs"

[dependencies]
serde = "1.0.45"
serde_json = "1.0.17"
serde_derive = "1.0.45"
